<?php

define('META_DESCRIPTION', 'Система цифрового мережування Громадянське Суспільство.');
define('BEACON', 'Маячок.');
define('BEACONS', 'Маячки');
define('GUEST', 'Гість');
define('MAIN_MENU', 'Головне меню');
define('OPTIONS','Опції');
define('ADDRESS','Адреса');
define('NEARBY','Поруч');
define('LOCATION','Місце');
define('FAVORITE', 'Обрані');
define('ADD','Додати');
define('SHARE','Поширити');
define('FAVORITE_BEACONS', 'Обрані маячки');
define('CLOSE', 'Закрити');
define('ABUSE', 'Зловживання');
define('MAP', 'Карта');
define('MY_ACTIVITIES', 'Мої активності');
define('MY_TASKS', 'Мої завдання');
define('MY_PROFILE', 'Мій профіль');
define('HELP', 'Довідка');
define('LOGIN', 'Вхід');
define('LOGOUT', 'Вихід');
define('USER RATING', 'Рейтинг користувача');
define('CATEGORIES', 'Категорії');
define('TIME_RANGE', 'Проміжок часу');
define('BEACON_STATUS', 'Статус маячка');
define('ACTIONS', 'Дії');
define('AUTH_TITLE', 'Показати маячки від громадян, авторизованих');
define('ALL', 'Всі');
define('AUTH_EMAIL', 'за електронною поштою');
define('AUTH_PAYMENT', 'за платежем');
define('AUTH_BANKID', 'за BankID');
define('AUTH_SOCIAL', 'за соціальною мережею');
define('AUTH_ORG', 'організацією');
define('AUTH_COOWNERS', 'як співвласники');
define('BEACONS_SHOW', 'Показати маячки');
define('LAST_ANY','За весь час');
define('LAST_HOUR','За останню годину');
define('LAST_DAY', 'За останній день');
define('LAST_WEEK', 'За останній тиждень');
define('LAST_MONTH', 'За останні 30 днів');
define('LAST_HUNDRED', 'За останні 100 днів');
define('LAST_YEAR','За останній рік');
define('CUSTOM_RANGE','Встановити межі');
define('FROM','з');
define('TO','по');
define('DATE_PLACEHOLDER','дд.мм.рррр');
define('BEACONS_SHOW_ONLY','Показати маячки тільки');
define('BEACONS_NEW','Нові');
define('BEACONS_CONFIRMED','Підтверджені');
define('BEACONS_PROCESSING','В стані обробки');
define('BEACONS_CLOSED','Закриті');
define('BEACONS_SHOW_ONLY_USERS','Показати маячки користувачів тільки');
define('VOTINGS','Голосування');
define('PROGRAMMS','Програми');
define('PROJECT_PROPOSALS','Проектні пропозиції');
define('PROJECTS','Проекти');
define('REQUESTS','Запити');
define('BUDGET','Бюджет участі');
define('POSITIVE','Тут добре');
define('NEGATIVE','Тут погано');
define('IMPORTANT','Важливо');
define('SOS','СОС');
define('ENTER', 'Вхід');
define('EMAIL','Електронна пошта');
define('PASSWORD','Пароль');
define('ENTER_SOCIAL','Приєднатися через мережу');
define('QUESTION_FIRST_TIME','Ви тут вперше?');
define('QUESTION_RESTORE_PASSWORD','Забули пароль?');
define('REGISTER_CORPORATE', 'Реєстрація юридичної особи');
define('REGISTER','Реєстрація');
define('REGISTER_NOW', 'Зареєструватись');
define('REMOVE', 'Видалити');
define('PROTOTYPE', 'Прототип');
define('NICKNAME', 'Нік');
define('PASSWORD','Пароль');
define('PASSWORD_REPEAT','Повторіть пароль');
define('PASSWORD_RESTORE','Відновлення паролю');
define('PASSWORD_RESET','Зкидання паролю');
define('PASSWORD_RESET_NOW','Зкинути пароль');
define('RESTORE','Відновити');
define('BEACON_RELATED','пов`язаного з маячком id=<%- parent_id %>');
define('AS_COPY_OF_BEACON','як копії маячка id=<%- targetId %>');
define('CREATE','Створити');
define('REQUIRED_FIELDS','* - Обов`язкові поля.');
define('COORDINATES','Координати');
define('LAT','ш.');
define('LNG','д.');
define('MESSAGE_CAN_MOVE_BEACON', 'Можете перетягнути його в іншу точку на карті.');
define('LAYER','Шар');
define('REQUIRED_AMOUNT','Запитувана сума');
define('TITLE','Назва');
define('IN_CURRENCY', 'у валюті');
define('FUNDING_PERIOD','Дата початку збору коштів');
define('FUNDING_FINISH', 'Дата завершення збору коштів');
define('SELECT_BENEFICIARY', 'Визначте вигодонабувача');
define('CHOOSE_CURRENCY','Виберіть валюту');
define('NCO_BID','Запропонуйте неприбуткову організацію для адміністрування проекту');
define('MESSAGE_AUTOCOMPLITE','Автодоповнення починається з першої літери.');
define('CHOOSE_NCO', 'Оберіть організацію...');
define('DESCRIPTION_FULL', 'Детальний опис');
define('DESCRIPTION_PLACEHOLDER','Розмістіть детальний опис тут.');
define('RESPONSE_EXPECTED','Очікувана відповідь');
define('RESPONSE_TYPE','Тип відповіді');
define('DETAILS','Повідомлення');
define('DETAILS_PLACEHOLDER','Довжина повідомлення - до 240 символів.');
define('FLIP_TOGGLE_SWITCH_CHECKBOX','Flip toggle switch checkbox:');
define('FOR_GROUP', 'Для групи');
define('MESSAGE_PUBLIC','Публічний');
define('SELECT_GROUP','Оберіть групу');
define('MESSAGE_AUTOCOMPLITE3','Автодоповнення починається <strong>з третьої літери</strong>');
define('GROUP_NAME_PLACEHOLDER','Назва групи');
define('TAG_ADD','Додати тег');
define('PRESS_ENTER', 'Для завершення натисніть Enter.');
define('ADD_TAG_PLACEHOLDER', '# лише букви та цифри');
define('MESSAGE_ONLY_LETTERS_DIGITS','Вводьте лише букви та цифри.');
define('PHOTO_UPLOAD','Завантажити фото:');
define('PHOTO_CHOOSE_FILE','Оберіть фото');
define('PHONE_NUMBER','Номер телефону');
define('ADMIN_LEVEL_SELECT','Виберіть адміністративний рівень проекту');
define('ADMIN_LEVEL_CITY','Місто');
define('ADMIN_LEVEL_CITY_DISTRICT','Район міста');
define('AGE_RANGE','Вікові межі голосуючих');
define('MIN_SUPPORT_VOTES','Мінімальна кількість голосів для початку голосування');
define('SUPPORT_FINISH_DATE','Дата завершення збору голосів підтримки');
define('CHOOSE_SPHERE','Виберіть сферу голосування');
define('LEFT_ICON', 'Left Icon');
define('FROM','від');
define('ICON','Icon');
define('STATUS','Status');
define('PHOTO','Photo');
define('ENHANCED_ICON_ONLY','Enhanced - Icon only');
define('SHARE','Share');
define('LINK','Link');
define('DISPROVE','Disprove');
define('ADD_TO_FAVORITE','Add to Favorite');
define('ADD_NEW','Add New');
define('SEND','Відправити');
define('MESSAGE_PLACEHOLDER','Повідомлення');
define('POST','Надіслати');
define('EMPTY_BEACON_LIST','За обраними параметрами мапи та фільтрів<br>позначки/маячки користувачів тут відсутні');
define('PHONE','Тел.');
define('ABUSE-SPAM','Поскажитись');
define('PROJECT_COST','Орієнтовна вартість проекту');
define('DESCRIPTION_FULL_PROJECT','Детальний опис проекту');
define('SUPPORTED_VOTES','Зібрано <strong><%- sprtd %></strong> голосів підтримки з <strong><%- sprt %></strong> необхідних.');
define('SUPPORT_LAST_DATE','Дата завершення збору підтримки');
define('VOTE_START_DATE','Дата початку голосування');
define('VOTE_FINISH_DATE','Дата завершення голосування');
define('VOTE_SPHERE','Сфера голосування');
define('VOTE_STATUS','Статус голосування');
define('VOTE_DESCUSSION','Обговорення голосування');
define('YOUR_AUTH_LEVEL','Рівень Вашої авторизації');
define('YOUR_STATUS','Ваш статус');
define('VOTE_NOW','Голосувати');
define('VOTE_ANONYMOUS','Таємно');
define('VOTE_OPEN','Відкрито');
define('VOTE_NO','Проти');
define('VOTE_ABSTAIN','Утриматись');
define('VOTE_YES','За');
define('IN_PERCENTS','У відсотках');
define('TOTAL','Всього');
define('PROGRAM_DESCRIPTION','Опис програми');
define('PROGRAM_ID','ID програми');
define('PROGRAM_DISCUSSION','Обговорення програми');
define('NUMBER_OF_PP','Проектних пропозицій');
define('PP_LIST','Перелік');
define('DONATE','Пожертвувати');
define('TO_PROGRAM','До програми ID');
define('BENEFICIARY','Бенефіціар');
define('SUM_REQUESTED','Сума запитувана');
define('NCO_NOT_SELECTED_BY_AUTHOR','Автор не визначився з бажаною НКО.');
define('NCO_SELECTED_BY_AUTHOR','Автор хотів би співпрацювати з НКО');
define('ACCEPT_PROPOSAL','Прийняти пропозицію');
define('CALL_OFF','Відкликати');
define('MAP_SEARCH_PLACEHOLDER','#хеш-тег чи числовий id');
define('NEARBY','nearby');
define('LOCATION','location');
define('FAVORITE_LIST','Список обраного');
define('SHARE','share');
define('BEACON_CREATE_MESSAGE','Щоб створити новий шар <br> натисніть ліву кнопку');
define('CHANGE_MENU','Змінити меню');
define('ADD_MORE','Додати ще');
define('SAVE','Зберегти');
define('ADD_LAYER_TITLE','Додайте назву шару"');
define('YOUR_EMAIL','Ваша електронна пошта');
define('CLICK_TO_EXPAND_CONTENTS','click to expand contents');
define('BEACONS_OF_CORPS_SHOW','Показати маячки організацій:');
define('CLEAR_TEXT','Clear text');
define('CLOSE_INPUT','Close input');

?>
