<?php

define('META_DESCRIPTION', 'Система цифрового взаимодействия Гражданское Общество.');
define('BEACON', 'Маячок.');
define('BEACONS', 'Маячки');
define('GUEST', 'Гость');
define('MAIN_MENU', 'Главное меню');
define('OPTIONS','Опции');
define('ADDRESS','Адрес');
define('NEARBY','Рядом');
define('LOCATION','Место');
define('FAVORITE', 'Избранные');
define('ADD','Добавить');
define('SHARE','Распространить');
define('FAVORITE_BEACONS', 'Избранные маячки');
define('CLOSE', 'Закрыть');
define('ABUSE', 'Злоупотребление');
define('MAP', 'Карта');
define('MY_ACTIVITIES', 'Мои активности');
define('MY_TASKS', 'Мои задания');
define('MY_PROFILE', 'Мой профиль');
define('HELP', 'Справка');
define('LOGIN', 'Вход');
define('LOGOUT', 'Выход');
define('USER RATING', 'Рейтинг пользователя');
define('CATEGORIES', 'Категории');
define('TIME_RANGE', 'Промежуток времени');
define('BEACON_STATUS', 'Статус маячка');
define('ACTIONS', 'Действия');
define('AUTH_TITLE', 'Показать маячки от граждан, авторизованных');
define('ALL', 'Все');
define('AUTH_EMAIL', 'электронной почтой');
define('AUTH_PAYMENT', 'по платежу');
define('AUTH_BANKID', 'по BankID');
define('AUTH_SOCIAL', 'через социальную сеть');
define('AUTH_ORG', 'организацией');
define('AUTH_COOWNERS', 'как совладелец');
define('BEACONS_SHOW', 'Показать маячки');
define('LAST_ANY','За всё время');
define('LAST_HOUR','За последний час');
define('LAST_DAY', 'За последний день');
define('LAST_WEEK', 'За последнюю неделю');
define('LAST_MONTH', 'За последние 30 дней');
define('LAST_HUNDRED', 'За последние 100 дней');
define('LAST_YEAR','За последний год');
define('CUSTOM_RANGE','Установить границы');
define('FROM','с');
define('TO','по');
define('DATE_PLACEHOLDER','дд.мм.гггг');
define('BEACONS_SHOW_ONLY','Показать маячки только');
define('BEACONS_NEW','Новые');
define('BEACONS_CONFIRMED','Подтвержденные');
define('BEACONS_PROCESSING','В состоянии обработки');
define('BEACONS_CLOSED','Закрытые');
define('BEACONS_SHOW_ONLY_USERS','Показать маячки пользователей только');
define('VOTINGS','Голосования');
define('PROGRAMMS','Программы');
define('PROJECT_PROPOSALS','Проектные предложения');
define('PROJECTS','Проекты');
define('REQUESTS','Запросы');
define('BUDGET','Бюджет участия');
define('POSITIVE','Здесь хорошо');
define('NEGATIVE','Здесь плохо');
define('IMPORTANT','Важно');
define('SOS','СОС');
define('ENTER', 'Вход');
define('EMAIL','Электронная почта');
define('PASSWORD','Пароль');
define('ENTER_SOCIAL','Присоединиться через сеть');
define('QUESTION_FIRST_TIME','Вы здесь впервые?');
define('QUESTION_RESTORE_PASSWORD','Забыли пароль?');
define('REGISTER_CORPORATE', 'Регистрация юридического лица');
define('REGISTER','Регистрация');
define('REGISTER_NOW', 'Зарегистрироваться');
define('REMOVE', 'Удалить');
define('PROTOTYPE', 'Прототип');
define('NICKNAME', 'Ник');
define('PASSWORD','Пароль');
define('PASSWORD_REPEAT','Повторите пароль');
define('PASSWORD_RESTORE','Восстановление пароля');
define('PASSWORD_RESET','Сброс пароля');
define('PASSWORD_RESET_NOW','Сбросить пароль');
define('RESTORE','Востановить');
define('BEACON_RELATED','связанного с маячком id=<%- parent_id %>');
define('AS_COPY_OF_BEACON','как копии маячка id=<%- targetId %>');
define('CREATE','Создать');
define('REQUIRED_FIELDS','* - Обязательные поля.');
define('COORDINATES','Координаты');
define('LAT','ш.');
define('LNG','д.');
define('MESSAGE_CAN_MOVE_BEACON', 'Можете перетащить его в другую точку на карте.');
define('LAYER','Слой');
define('REQUIRED_AMOUNT','Запрашиваемая сумма');
define('TITLE','Название');
define('IN_CURRENCY', 'в валюте');
define('FUNDING_PERIOD','Дата начала сбора средств');
define('FUNDING_FINISH', 'Дата завершения сбора средств');
define('SELECT_BENEFICIARY', 'Определите выгодоприобретателя');
define('CHOOSE_CURRENCY','Выберите валюту');
define('NCO_BID','Предложите неприбыльную организацию для администрирования проекта');
define('MESSAGE_AUTOCOMPLITE','Автозаполнения начинается с первой буквы.');
define('CHOOSE_NCO', 'Выберите организацию...');
define('DESCRIPTION_FULL', 'Детальное описание');
define('DESCRIPTION_PLACEHOLDER','Разместите подробное описание здесь.');
define('RESPONSE_EXPECTED','Ожидаемый ответ');
define('RESPONSE_TYPE','Тип ответа');
define('DETAILS','Сообщение');
define('DETAILS_PLACEHOLDER','Длина сообщения - до 240 символов.');
define('FLIP_TOGGLE_SWITCH_CHECKBOX','Flip toggle switch checkbox:');
define('FOR_GROUP', 'Для группы');
define('MESSAGE_PUBLIC','Публичный');
define('SELECT_GROUP','Выберите группу');
define('MESSAGE_AUTOCOMPLITE3','Автозаполнение начинается <strong>с третьей буквы</strong>');
define('GROUP_NAME_PLACEHOLDER','Название группы');
define('TAG_ADD','Добавить тег');
define('PRESS_ENTER', 'Для завершения нажмите Enter.');
define('ADD_TAG_PLACEHOLDER', '# только буквы и цифры');
define('MESSAGE_ONLY_LETTERS_DIGITS','Вводите только буквы и цифры.');
define('PHOTO_UPLOAD','Загрузить фото:');
define('PHOTO_CHOOSE_FILE','Выберите фото');
define('PHONE_NUMBER','Номер телефона');
define('ADMIN_LEVEL_SELECT','Выберите административный уровень проекта');
define('ADMIN_LEVEL_CITY','Город');
define('ADMIN_LEVEL_CITY_DISTRICT','Район города');
define('AGE_RANGE','Возрастные границы голосующих');
define('MIN_SUPPORT_VOTES','Минимальное количество голосов для начала голосования');
define('SUPPORT_FINISH_DATE','Дата завершения сбора голосов поддержки');
define('CHOOSE_SPHERE','Выберите сферу голосования');
define('LEFT_ICON', 'Левая иконка');
define('FROM','от');
define('ICON','Иконка');
define('STATUS','Статус');
define('PHOTO','Фото');
define('ENHANCED_ICON_ONLY','Повисить - только иконка');
define('SHARE','Поделиться');
define('LINK','Ссылка');
define('DISPROVE','Опровергнуть');
define('ADD_TO_FAVORITE','Добавить в издранное');
define('ADD_NEW','Добавить новый');
define('SEND','Отправить');
define('MESSAGE_PLACEHOLDER','Сообщение');
define('POST','Отослать');
define('EMPTY_BEACON_LIST','По выбранным параметрам карты и фильтров<br>отметки / маячки пользователей здесь отсутствуют');
define('PHONE','Тел.');
define('ABUSE-SPAM','Пожаловаться');
define('PROJECT_COST','Ориентировочная стоимость проекта');
define('DESCRIPTION_FULL_PROJECT','Детальное описание проекта');
define('SUPPORTED_VOTES','Собрано <strong><%- sprtd %></strong> голосов поддержки из <strong><%- sprt %></strong> необходимых.');
define('SUPPORT_LAST_DATE','Дата завершения сбора поддержки');
define('VOTE_START_DATE','Дата начала голосования');
define('VOTE_FINISH_DATE','Дата завершения голосования');
define('VOTE_SPHERE','Сфера голосования');
define('VOTE_STATUS','Статус голосования');
define('VOTE_DESCUSSION','Обсуждение голосования');
define('YOUR_AUTH_LEVEL','Уровень Вашей авторизации');
define('YOUR_STATUS','Ваш статус');
define('VOTE_NOW','Голосовать');
define('VOTE_ANONYMOUS','Тайно');
define('VOTE_OPEN','Открыто');
define('VOTE_NO','Против');
define('VOTE_ABSTAIN','Воздержаться');
define('VOTE_YES','За');
define('IN_PERCENTS','в процентах');
define('TOTAL','Всего');
define('PROGRAM_DESCRIPTION','Описание программы');
define('PROGRAM_ID','ID программы');
define('PROGRAM_DISCUSSION','Обсуждение программы');
define('NUMBER_OF_PP','Проектных предложений');
define('PP_LIST','Перечень');
define('DONATE','Пожертвовать');
define('TO_PROGRAM','На программу ID');
define('BENEFICIARY','Бенефициар');
define('SUM_REQUESTED','Сумма запрашиваемая');
define('NCO_NOT_SELECTED_BY_AUTHOR','Автор не определился с желаемой НКО.');
define('NCO_SELECTED_BY_AUTHOR','Автор хотел бы сотрудничать с НКО');
define('ACCEPT_PROPOSAL','Принять предложение');
define('CALL_OFF','Отозвать');
define('MAP_SEARCH_PLACEHOLDER','#хеш-тег или числовой id');
define('NEARBY','Рядом');
define('LOCATION','Расположение');
define('FAVORITE_LIST','Список избранного');
define('SHARE','Поделиться');
define('BEACON_CREATE_MESSAGE','Чтобы создать новый слой <br> нажмите левую кнопку');
define('CHANGE_MENU','Изменить меню');
define('ADD_MORE','Добавить еще');
define('SAVE','Сохранить');
define('ADD_LAYER_TITLE','Добавьте название слоя');
define('YOUR_EMAIL','Ваша электронная почта');
define('CLICK_TO_EXPAND_CONTENTS','нажмите, чтобы открыть содержимое');
define('BEACONS_OF_CORPS_SHOW','Показать маячки организаций:');
define('CLEAR_TEXT','Очистить текст');
define('CLOSE_INPUT','Закрить ввод');

?>
