<?php


define('ABUSE', 'Abuse');
define('ABUSE-SPAM','abuse report');
define('ACCEPT_PROPOSAL','Accept the proposal');
define('ACTIONS', 'Actions');
define('ADD','Add');
define('ADDRESS','Addres');
define('ADD_LAYER_TITLE','Please add the title of layer');
define('ADD_MORE','Add more');
define('ADD_NEW','Add New');
define('ADD_TAG_PLACEHOLDER', '# only letters and numbers');
define('ADD_TO_FAVORITE','Add to Favorite');
define('ADMIN_LEVEL_CITY','City');
define('ADMIN_LEVEL_CITY_DISTRICT','City district');
define('ADMIN_LEVEL_SELECT','Choose an administrative level of project');
define('AGE_RANGE','Age range of voters');
define('ALL', 'All');
define('AS_COPY_OF_BEACON','as copy of beacon id =<%- targetId %>');
define('AUTH_BANKID', 'via BankID');
define('AUTH_COOWNERS', 'as coowners');
define('AUTH_EMAIL', 'via email');
define('AUTH_ORG', 'via organisation');
define('AUTH_PAYMENT', 'via payment');
define('AUTH_SOCIAL', 'via social network');
define('AUTH_TITLE', 'Show the beacons of citizens who authorised via');
define('BEACON', 'Beacon.');
define('BEACONS', 'Beacons');
define('BEACONS_CLOSED','Terminated');
define('BEACONS_CONFIRMED','Verified');
define('BEACONS_NEW','New');
define('BEACONS_OF_CORPS_SHOW','Show beacons of organisations:');
define('BEACONS_PROCESSING','Under processing');
define('BEACONS_SHOW', 'Show the beacons');
define('BEACONS_SHOW_ONLY','Show the beacons only');
define('BEACONS_SHOW_ONLY_USERS','Show only such the users\' beacons');
define('BEACON_CREATE_MESSAGE','To create new layer  <br> please push left button');
define('BEACON_RELATED','which linked with beacons id =<%- parent_id %>');
define('BEACON_STATUS', 'Beacon status');
define('BENEFICIARY','Beneficiary');
define('BUDGET','Participative budgeting');
define('CALL_OFF','Withdraw');
define('CATEGORIES', 'Categoties');
define('CHANGE_MENU','Change menu');
define('CHOOSE_CURRENCY','Select currency');
define('CHOOSE_NCO', 'Choose the NGO...');
define('CHOOSE_SPHERE','Choose the sphere of voting');
define('CLEAR_TEXT','Clear text');
define('CLICK_TO_EXPAND_CONTENTS','click to expand contents');
define('CLOSE', 'Close');
define('CLOSE_INPUT','Close input');
define('COORDINATES','geographical coordinates');
define('CREATE','Create');
define('CUSTOM_RANGE','Set up the range');
define('DATE_PLACEHOLDER','dd/mm/yyyy');
define('DESCRIPTION_FULL', 'Full description');
define('DESCRIPTION_FULL_PROJECT','Full project description');
define('DESCRIPTION_PLACEHOLDER','Place the full description here.');
define('DETAILS','Notifications');
define('DETAILS_PLACEHOLDER','The lenght of the notification no more 240 characters.');
define('DISPROVE','Disprove');
define('DONATE','Donate');
define('EMAIL','Email');
define('EMPTY_BEACON_LIST','According with chosen parameters of map and filters<br>there are no marks/beacons');
define('ENHANCED_ICON_ONLY','Enhanced - Icon only');
define('ENTER', 'Login');
define('ENTER_SOCIAL','Login via social network');
define('FAVORITE', 'Selected');
define('FAVORITE_BEACONS', 'Selected beacons');
define('FAVORITE_LIST','Favorite list');
define('FLIP_TOGGLE_SWITCH_CHECKBOX','Flip toggle switch checkbox:');
define('FOR_GROUP', 'For group');
define('FROM','From');
define('FROM','from');
define('FUNDING_FINISH', 'Expiry date of crowdfunding');
define('FUNDING_PERIOD','Date to start crowdfunding');
define('GROUP_NAME_PLACEHOLDER','Group name');
define('GUEST', 'Guest');
define('HELP', 'Help');
define('ICON','Icon');
define('IMPORTANT','Important');
define('IN_CURRENCY', 'currency');
define('IN_PERCENTS','Percentage');
define('LAST_ANY','For all the time');
define('LAST_DAY', 'For the last day');
define('LAST_HOUR','For the last hour');
define('LAST_HUNDRED', 'Over the past 100 days');
define('LAST_MONTH', 'Over the past 30 days');
define('LAST_WEEK', 'In the last week');
define('LAST_YEAR','In the last year');
define('LAT','longitude.');
define('LAYER','Layer');
define('LEFT_ICON', 'Left Icon');
define('LINK','Link');
define('LNG','latitude.');
define('LOCATION','Location');
define('LOCATION','location');
define('LOGIN', 'Login');
define('LOGOUT', 'Logout');
define('MAIN_MENU', 'Main menu');
define('MAP', 'Map');
define('MAP_SEARCH_PLACEHOLDER','#hashtag or numeral id');
define('MESSAGE_AUTOCOMPLITE','Autofill start from the first letter  починається з першої літери.');
define('MESSAGE_AUTOCOMPLITE3','Autofilling start <from third letter</strong>'); 
define('MESSAGE_CAN_MOVE_BEACON', 'You can move it to another spot on the map.');
define('MESSAGE_ONLY_LETTERS_DIGITS','Please enter only letters and numbers.');
define('MESSAGE_PLACEHOLDER','Notification');
define('MESSAGE_PUBLIC','Open');
define('META_DESCRIPTION', 'Digital networking system Civil Society.');
define('MIN_SUPPORT_VOTES','Minimal amount of votes to start voting');
define('MY_ACTIVITIES', 'My activities');
define('MY_PROFILE', 'My profile');
define('MY_TASKS', 'My tasks');
define('NCO_BID','Assign the NGO for administering of project');
define('NCO_NOT_SELECTED_BY_AUTHOR','The author is undecided with the appropriate NGO.');
define('NCO_SELECTED_BY_AUTHOR','Author would cooperate with the NGO');
define('NEARBY','Nearby');
define('NEARBY','nearby');
define('NEGATIVE','Here is bad');
define('NICKNAME', 'Nickname');
define('NUMBER_OF_PP','Project proposals');
define('OPTIONS','Features');
define('PASSWORD','Password');
define('PASSWORD','Password');
define('PASSWORD_REPEAT','Repeat password');
define('PASSWORD_RESET','Password reset');
define('PASSWORD_RESET_NOW','reset password now');
define('PASSWORD_RESTORE','Restore password');
define('PHONE','Phone.');
define('PHONE_NUMBER','Phone number');
define('PHOTO','Photo');
define('PHOTO_CHOOSE_FILE','Choose the photo');
define('PHOTO_UPLOAD','Photo upload:');
define('POSITIVE','Here is good');
define('POST','Post');
define('PP_LIST','List');
define('PRESS_ENTER', 'For completing to press Enter.');
define('PROGRAMMS','Programs');
define('PROGRAM_DESCRIPTION','Program description');
define('PROGRAM_DISCUSSION','Discussion of the program');
define('PROGRAM_ID','ID of Program');
define('PROJECTS','Projects');
define('PROJECT_COST','Approximate cost of project');
define('PROJECT_PROPOSALS','Project proposals');
define('PROTOTYPE', 'Prototype');
define('QUESTION_FIRST_TIME','Is it your first visit?');
define('QUESTION_RESTORE_PASSWORD','Forgot password?');
define('REGISTER','Registration');
define('REGISTER_CORPORATE', 'Legal entity registration');
define('REGISTER_NOW', 'Register now');
define('REMOVE', 'Remove');
define('REQUESTS','Requests');
define('REQUIRED_AMOUNT','Required sum');
define('REQUIRED_FIELDS','* - Required fields.');
define('RESPONSE_EXPECTED','Expected response');
define('RESPONSE_TYPE','Type of response');
define('RESTORE','Restore');
define('SAVE','Save');
define('SELECT_BENEFICIARY', 'Select the beneficiary');
define('SELECT_GROUP','Choose the group');
define('SEND','Send');
define('SHARE','Share');
define('SHARE','Share');
define('SHARE','share');
define('SOS','SOS');
define('STATUS','Status');
define('SUM_REQUESTED','Requested sum');
define('SUPPORTED_VOTES','Collected <strong><%- sprtd %></strong> support votes out of <strong><%- sprt %></strong> needed.');
define('SUPPORT_FINISH_DATE','Final date of gathering supporting votes');
define('SUPPORT_LAST_DATE','Last date of gathering the supporting votes');
define('TAG_ADD','Add the tag');
define('TIME_RANGE', 'Time interval');
define('TITLE','Title');
define('TO','To');
define('TOTAL','Total');
define('TO_PROGRAM','To program ID');
define('USER RATING', 'User raiting');
define('VOTE_ABSTAIN','Abstain');
define('VOTE_ANONYMOUS','Secret vote');
define('VOTE_DESCUSSION','Discussion of voting');
define('VOTE_FINISH_DATE','Date of voting finishing');
define('VOTE_NO','Vote against');
define('VOTE_NOW','Vote now');
define('VOTE_OPEN','Open vote');
define('VOTE_SPHERE','Sphere of voting');
define('VOTE_START_DATE','Start date of voting');
define('VOTE_STATUS','Status of voting');
define('VOTE_YES','Vote Yes');
define('VOTINGS','Votings');
define('YOUR_AUTH_LEVEL','Your authorisation level');
define('YOUR_EMAIL','Your email');
define('YOUR_STATUS','Your status');
?>
